apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - mountPath: /tmp/cache-1
          name: cache-volume

    - name: c2
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      volumeMounts:
        - mountPath: /tmp/cache-2
          name: cache-volume

  volumes:
    - name: cache-volume
      emptyDir: {}






# console.disableYellowBox = true;