apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 2Gi    #request for a storage from PV
  accessModes:
    - ReadWriteOnce
  storageClassName: slow     #storageclassname should match with PV to bound with it 
