apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: con-1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-secret; sleep 5; done"]
    volumeMounts:
      - mountPath: "/tmp/mysecrets"       # the secret files will be mounted as readonly by default here
        name: test-secret
  volumes:
    - name: test-secret          #test-secret dir where we will find secretname file
      secret:
         secretName: mysecret     #this should be the same as secret file name



            # console.disableYellowBox = true;