apiVersion: v1
kind: Pod
metadata:
  name: multi-con-pod
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: redis
      
    - name: frontend
      image: django
      