apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-nodeport
  template:
    metadata:
      labels:
        app: label-nodeport
    spec:
      containers:
        - name: apache
          image: httpd
