name: yamllint

on: [push, pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: './.github/workflows/maven.yml'
        yamllint_strict: false
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
